name : Generate Podcast Feeds
on: [push] #when somebody pushes something on the main branch, it triggers the automation process (= execute this action)
jobs: 
  build: 
    runs-on: ubuntu-latest #specify the kind of machine it runs into
    steps: 
      - name: Checkout Repo #not mandatory to name the steps
        uses: actions/checkout@v3 
      - name: Run Feed Generator
        uses: a9athe/podcast-generator-LKexample@main #uses our other depo to set up the environment and do the git actions
        
        
          
        
